name: Publish Cirrus container

on:
  push:
    branches: ['UE5.3']
    paths: ['SignallingWebServer/**']

jobs:
  signalling-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push the Signalling Server container image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: 'ghcr.io/epicgames/pixel-streaming-signalling-server:5.3'
          push: true
          file: SignallingWebServer/Dockerfile
