name: Run Stream Test

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Client
        working-directory: ./Testing/StreamTest/TestClient
        run: npm build
      - name: Run Test
        working-directory: ./Testing/StreamTest
        run: npm start
